### ISSUE TITLE
If base_path isn't set then Object.URI is wrong.

### ISSUE THREAD

**Issue by jcoyne** [projecthydra/active_fedora#680] opened 2015-01-08 16:41 UTC
If I don't have base_path set in fedora.yml
then when I create an object: `o = ActiveFedora::Base.find('5831ea7c-64c2-4870-8001-8d1ce533ebce')`
then its uri has a blank path segment (`//`) in it. i.e. 
"http://127.0.0.1:8080/fedora/rest//58/31/ea/7c/5831ea7c-64c2-4870-8001-8d1ce533ebce"

The graph returned from accessing that path, doesn't have the blank path segment, so the assertions are not returned.

**Comment by jcoyne** [comment] 2015-01-13 21:20
To elaborate, there is no reason a user must configure 'base_path', it's just a convenience for scoping your current connection to a specific subset of URIs

**Comment by hectorcorrea** [comment] 2015-01-22 20:44
Duplicate of issue #657 
Fixed in PR #696

**Closed by hectorcorrea** 2015-01-22 20:44 UTC
